# Generated by Django 4.2.1 on 2023-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('version', models.CharField(blank=True, max_length=60, null=True)),
                ('card_number', models.CharField(blank=True, max_length=10, null=True)),
                ('rarity', models.CharField(blank=True, max_length=1, null=True)),
                ('rules', models.CharField(blank=True, max_length=570, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=40, null=True)),
                ('mutant', models.CharField(blank=True, max_length=30, null=True)),
                ('flight', models.IntegerField(blank=True, null=True)),
                ('range', models.IntegerField(blank=True, null=True)),
                ('visible', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
