# Generated by Django 4.2.1 on 2023-10-25 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
