# Generated by Django 4.2.1 on 2023-10-25 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20231024_2349"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decks",
            options={},
        ),
    ]
