# Generated by Django 4.2.7 on 2024-04-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_auto_20231024_2207"),
        ("core", "0007_alter_decks_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="decks",
            name="main_card",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="decks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="decks",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
    ]
