# Generated by Django 4.2.7 on 2024-04-29 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_decks_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decks",
            name="main_card",
        ),
    ]
