# Generated by Django 4.2.7 on 2024-04-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_decks_main_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="decks",
            name="main_card",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
