# Generated by Django 4.2.7 on 2025-05-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_decks_main_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='main_card',
        ),
    ]
