# Generated by Django 4.2.1 on 2023-05-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_decks_unique_together_decks_deck_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='decks',
            unique_together={('deck_id', 'card_id')},
        ),
        migrations.RemoveField(
            model_name='decks',
            name='deck_card_id',
        ),
    ]
