# Generated by Django 4.2.1 on 2023-05-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_decks_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='decks',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='decks',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
