# Generated by Django 4.2.1 on 2023-05-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_decks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cards'),
        ),
        migrations.AlterField(
            model_name='decks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
