# Generated by Django 4.2.1 on 2023-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_decks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
