# Generated by Django 4.2.1 on 2023-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_decks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
