# Generated by Django 4.2.1 on 2023-05-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_decks_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='id',
        ),
        migrations.AddField(
            model_name='decks',
            name='poop',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
