# Generated by Django 4.2.1 on 2023-05-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_decks_id_decks_poop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('image_name', models.CharField(max_length=50)),
                ('image_type', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'card_images',
            },
        ),
        migrations.RemoveField(
            model_name='decks',
            name='poop',
        ),
        migrations.AddField(
            model_name='decks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
